language: cpp

# os:
#  - linux
#  - osx

compiler:
#  - gcc
  - clang

env:
  - CGAL_VERSION=4.3
  - CGAL_VERSION=4.7

before_install:
  - ./travis/${TRAVIS_OS_NAME}/before_install.sh $CGAL_VERSION

before_script:
  - cmake -DSFCGAL_BUILD_TESTS=ON

script:
  - make
  - make test
